spring:
    application:
        name: cashflow
    datasource:
        name: cashflow
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform=org: hibernate.dialect.H2Dialect
