spring:
    application:
        name: cashflow
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres  # Замените на свой URL
        username: myuser  # Замените на своё имя пользователя
        password: mypassword  # Замените на свой пароль
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
server:
  port : 8081